"""drop_remark_type

Revision ID: 1516d15a1bef
Revises: fc4b66102c67
Create Date: 2026-05-14 06:59:35.744717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1516d15a1bef'
down_revision: Union[str, Sequence[str], None] = 'fc4b66102c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_remarks', 'remark_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_remarks', sa.Column('remark_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
