"""add_submission_bins

Revision ID: 5ee10ec12f32
Revises: ab66dfea0e7a
Create Date: 2026-05-02 14:56:21.905710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee10ec12f32'
down_revision: Union[str, Sequence[str], None] = 'ab66dfea0e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_bins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('school_year', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('submission_bin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'submission_bins', ['submission_bin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'submission_bin_id')
    op.drop_table('submission_bins')
    # ### end Alembic commands ###
