"""add_avatar_url_to_scholars

Revision ID: ab66dfea0e7a
Revises: 3b9970469f0e
Create Date: 2026-05-02 07:43:42.083539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab66dfea0e7a'
down_revision: Union[str, Sequence[str], None] = '3b9970469f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholars', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholars', 'avatar_url')
    # ### end Alembic commands ###
