"""add_is_approved_to_submission_bins

Revision ID: cd81366cd8dd
Revises: 5ee10ec12f32
Create Date: 2026-05-02 15:45:50.403037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd81366cd8dd'
down_revision: Union[str, Sequence[str], None] = '5ee10ec12f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_bins', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_bins', 'is_approved')
    # ### end Alembic commands ###
