"""add_updated_at_and_system_sync

Revision ID: eeb1e72caa3a
Revises: cd81366cd8dd
Create Date: 2026-05-03 02:04:06.291445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb1e72caa3a'
down_revision: Union[str, Sequence[str], None] = 'cd81366cd8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_sync',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('academic_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('pending_changes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('submission_bins', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_bins', 'updated_at')
    op.drop_column('pending_changes', 'updated_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('academic_records', 'updated_at')
    op.drop_table('system_sync')
    # ### end Alembic commands ###
